language: ruby
branches:
    only:
        - master
env:
    global:
        secure: "D7M2tLMiycNxoIroM2Ur/BNyO2w81Mz5amj0WUTh7z2nqyPGQkY7TTP2jKcaJOspeDEetR98+L1V8iX909w9t4eg6ffIPs2TVi2znPc5cJjdPn2/pPlEQtXYZH6aanK4rp4xw5tT+aKdoqTKfjVnwBHVh2LDUE5UgjrSY2fQZziyeBTyvsecvcZtrB6rYLX3usvnpJEbKxejBFrhKrMoPlxf1THvfJrUbs0IdiBWboE02u+j41HIN47NoAPWsqP6p74sE7M3tEKMXBnbox8xkSWScJ/waVGpiHcDGIy+yX2qotSGhQ/kRPsiSk02Am3To8QDz37PeyOM/m4GI8zqX6kAVqtAhrHF+8G6CXKByQkW56X978QsLO6CYTchKlJetVWs6m1wl64bQsJzkYsFrNvnsw5Tu5bk0eu7Mh9p1qhPNeWIOiEZ9xJeuuQPdB9eEFQI4AUWEx2nEHLgeMZpJuyx6vWlDGYEqt6N4GJLq3KiuDweqFgBu/uhohfzWY3q38DFfohf4pe8XrsCzJxozxSSUQZH539Oc9W159dQ+okoiDuYKmZfHd/QTGtV5QNF+bt7Yh3xsdc3AoHrzU+T8R/eEIaKpBGMyd2segdYleMXU8LvrdNRl3UY4PNv6gVoMBPc93EMsXsMlrYPblkJQ9kIqoz1fmKdK1B35vD/0G0="
        - GH_OWNER=Haroenv
        - GH_PROJECT_NAME=bus
install:
    - bundle install
script:
    - jekyll build
after_success:
    # Any command that using GH_OAUTH_TOKEN must pipe the output to /dev/null to not expose your oauth token
    - git submodule add -b gh-pages https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site > /dev/null 2>&1
    - cd site
    - if git checkout gh-pages; then git checkout -b gh-pages; fi
    - git rm -r .
    - cp -R ../_site/* .
    - cp ../_site/.* .
    - git add -f .
    - git config user.email "hello@haroen.me"
    - git config user.name "Haroen Viaene (bot)"
    - git commit -am "built via travis [ci skip]"
    # Any command that using GH_OAUTH_TOKEN must pipe the output to /dev/null to not expose your oauth token
    - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1
