lang: en
author:
  name: Haroen Viaene
  email: hello@haroen.me
  twitter: '@haroenv'
title: bus tracker
description: a tracker for the location of a bus
url: https://haroen.me
baseurl: /bus
color: '#191f26'
css: /src/style.css
scripts: ['/src/main.js']
development: true
analytics: UA-27277115-3
sass:
  style: compressed
